# Generated by Django 3.2.9 on 2021-11-16 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexfac_core_api', '0002_auto_20211116_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='users',
            field=models.ManyToManyField(to='nexfac_core_api.User'),
        ),
        migrations.AddField(
            model_name='asset',
            name='users',
            field=models.ManyToManyField(to='nexfac_core_api.User'),
        ),
        migrations.AddField(
            model_name='task',
            name='areas',
            field=models.ManyToManyField(to='nexfac_core_api.Area'),
        ),
        migrations.AddField(
            model_name='task',
            name='assets',
            field=models.ManyToManyField(to='nexfac_core_api.Asset'),
        ),
    ]
