# Generated by Django 3.2.9 on 2021-11-16 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexfac_core_api', '0003_auto_20211116_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_inputs',
            field=models.JSONField(default={}),
        ),
    ]
