# Generated by Django 3.2.9 on 2021-11-16 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexfac_core_api', '0006_auto_20211116_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='users',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='users',
        ),
        migrations.RemoveField(
            model_name='task',
            name='areas',
        ),
        migrations.RemoveField(
            model_name='task',
            name='assets',
        ),
        migrations.AddField(
            model_name='area',
            name='tasks',
            field=models.ManyToManyField(to='nexfac_core_api.Task'),
        ),
        migrations.AddField(
            model_name='asset',
            name='tasks',
            field=models.ManyToManyField(to='nexfac_core_api.Task'),
        ),
        migrations.AddField(
            model_name='user',
            name='areas',
            field=models.ManyToManyField(to='nexfac_core_api.Area'),
        ),
        migrations.AddField(
            model_name='user',
            name='assets',
            field=models.ManyToManyField(to='nexfac_core_api.Asset'),
        ),
    ]
