# Generated by Django 3.2.9 on 2021-11-23 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexfac_core_api', '0007_auto_20211116_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='independent_task',
            field=models.BooleanField(null=True),
        ),
    ]
